import { watch } from "chokidar";
import {
  readdir,
  readFile,
  writeFile,
  mkdir,
  rename,
  unlink,
  stat,
  realpath,
} from "node:fs/promises";
import { existsSync } from "node:fs";
import {
  basename,
  dirname,
  extname,
  isAbsolute,
  join,
  relative,
  resolve,
  sep,
} from "node:path";
import { randomUUID } from "node:crypto";
import picomatch from "picomatch";
import prettier from "prettier";
import { analyzeFile, type FunctionInfo } from "./core/analyzer.js";
import { generateOptionsCode } from "./core/generator.js";
import {
  loadConfig,
  loadModule,
  resolveConfigPath,
  type ResolvedAutoQueryConfig,
  type CustomAnalyzerModule,
  type CustomTemplateModule,
} from "./config-loader.js";

const marker = "// Generated by @uiwwsw/react-query-helper. DO NOT EDIT.";
const configTemplate = `import type { AutoQueryConfig } from "@uiwwsw/react-query-helper/config";

export default {
  sourceDir: "./libs",
  outputDir: "./src/options",
  ignoredFiles: ["domain.ts", "adaptor.ts", "**/*.test.ts", "**/*.spec.ts"],
  template: { artifactStrategy: "smart" },
} satisfies AutoQueryConfig;
`;
const normalize = (path: string) => path.split(sep).join("/");
const within = (root: string, path: string) => {
  const rel = relative(root, path);
  return (
    rel === "" ||
    (rel !== ".." && !rel.startsWith(`..${sep}`) && !isAbsolute(rel))
  );
};
const processable = (path: string) =>
  /\.tsx?$/i.test(path) && !/\.d\.ts$/i.test(path);
async function physicalPath(path: string): Promise<string> {
  if (existsSync(path)) return realpath(path);
  return join(await physicalPath(dirname(path)), basename(path));
}
function ignored(config: ResolvedAutoQueryConfig, path: string) {
  if (
    [
      config.configPath,
      config.resolvedCustomAnalyzerPath,
      config.resolvedCustomTemplatePath,
    ].some((p) => p && isAbsolute(p) && resolve(p) === resolve(path))
  )
    return true;
  if (within(config.resolvedOutputDir, path)) return true;
  if (
    normalize(relative(config.resolvedSourceDir, path))
      .split("/")
      .some((p) => p === "node_modules" || p === ".git")
  )
    return true;
  return (config.ignoredFiles ?? []).some((pattern) =>
    picomatch(pattern, { dot: true, basename: !pattern.includes("/") })(
      normalize(relative(config.resolvedSourceDir, path)),
    ),
  );
}
async function walk(
  root: string,
  skip: (path: string) => boolean = () => false,
): Promise<string[]> {
  if (!existsSync(root)) return [];
  const result: string[] = [];
  for (const entry of (await readdir(root, { withFileTypes: true })).sort(
    (a, b) => a.name.localeCompare(b.name),
  )) {
    const path = join(root, entry.name);
    if (skip(path) || entry.isSymbolicLink()) continue;
    if (entry.isDirectory()) result.push(...(await walk(path, skip)));
    else if (entry.isFile()) result.push(path);
  }
  return result;
}
async function atomicWrite(path: string, content: string) {
  await mkdir(dirname(path), { recursive: true });
  const temp = `${path}.${randomUUID()}.tmp`;
  try {
    await writeFile(temp, content, { flag: "wx" });
    await rename(temp, path);
  } finally {
    await unlink(temp).catch(() => {});
  }
}
function modulePath(path: string, output: string) {
  const rel = normalize(relative(dirname(output), path));
  return rel.startsWith(".") ? rel : `./${rel}`;
}
function sourceImport(
  config: ResolvedAutoQueryConfig,
  path: string,
  output: string,
) {
  const withoutExtension = path.slice(0, -extname(path).length);
  const stripIndex = (p: string) => p.replace(/(?:\/index|^index)$/, "") || ".";
  if (config.sourceImportAlias) {
    const rel = stripIndex(
      normalize(relative(config.resolvedSourceDir, withoutExtension)),
    );
    return (
      config.sourceImportAlias.replace(/\/$/, "") +
      (rel === "." ? "" : `/${rel}`)
    );
  }
  return stripIndex(modulePath(withoutExtension, output));
}
async function plugin<T>(
  specifier: string | undefined,
  config: ResolvedAutoQueryConfig,
  method: string,
): Promise<T | undefined> {
  if (!specifier) return;
  const mod = await loadModule(specifier, config.configDir);
  const value = mod.default ?? mod;
  if (
    !value ||
    typeof (value as Record<string, unknown>)[method] !== "function"
  )
    throw new Error(`Plugin ${specifier} must export ${method}().`);
  return value as T;
}

async function generate(config: ResolvedAutoQueryConfig, check = false) {
  if (
    !existsSync(config.resolvedSourceDir) ||
    !(await stat(config.resolvedSourceDir)).isDirectory()
  )
    throw new Error(
      `sourceDir does not exist or is not a directory: ${config.resolvedSourceDir}`,
    );
  const sourceRoot = await realpath(config.resolvedSourceDir);
  const outputRoot = await physicalPath(config.resolvedOutputDir);
  if (within(outputRoot, sourceRoot))
    throw new Error("outputDir must not equal or contain sourceDir.");
  config.resolvedSourceDir = sourceRoot;
  config.resolvedOutputDir = outputRoot;
  const analyzer = await plugin<CustomAnalyzerModule>(
    config.resolvedCustomAnalyzerPath,
    config,
    "analyzeFile",
  );
  const template = await plugin<CustomTemplateModule>(
    config.resolvedCustomTemplatePath,
    config,
    "generateOptionsCode",
  );
  const owner = `${marker}\n// Source root: ${JSON.stringify(normalize(relative(config.resolvedOutputDir, config.resolvedSourceDir)))}\n`;
  const desired = new Map<string, string>();
  const targets = new Set<string>();
  for (const path of await walk(config.resolvedSourceDir, (p) =>
    ignored(config, p),
  )) {
    if (!processable(path)) continue;
    const rel = relative(config.resolvedSourceDir, path);
    const fileName = basename(path, extname(path));
    const output = join(
      config.resolvedOutputDir,
      dirname(rel),
      `${fileName}Options.ts`,
    );
    if (targets.has(output))
      throw new Error(`Output collision between .ts/.tsx sources: ${output}`);
    targets.add(output);
    const infos = analyzer
      ? await analyzer.analyzeFile(path, config)
      : analyzeFile(path, config.analyzer);
    if (
      !Array.isArray(infos) ||
      infos.some(
        (info) =>
          !info ||
          typeof info.name !== "string" ||
          !Array.isArray(info.parameters) ||
          info.parameters.some((p) => typeof p !== "string") ||
          typeof info.isExported !== "boolean" ||
          typeof info.isAsync !== "boolean",
      )
    )
      throw new Error(`Analyzer must return FunctionInfo[] for ${path}`);
    const params = {
      functionInfos: infos as FunctionInfo[],
      fileName,
      importPath: sourceImport(config, path, output),
      keySegments: dirname(rel) === "." ? [] : dirname(rel).split(sep),
      templateImportPath: isAbsolute(config.resolvedTemplateDir)
        ? modulePath(config.resolvedTemplateDir, output)
        : config.resolvedTemplateDir,
      config,
    };
    const code = template
      ? await template.generateOptionsCode(params)
      : generateOptionsCode(infos, params.importPath, {
          ...params,
          template: config.template,
        });
    if (typeof code !== "string")
      throw new Error(`Template must return a string for ${path}`);
    if (!code.trim()) continue;
    const formatting = await prettier.resolveConfig(output);
    desired.set(
      output,
      owner +
        (await prettier.format(code, { ...formatting, parser: "typescript" })),
    );
  }
  const stale: string[] = [];
  const existing = new Map<string, string>();
  for (const path of await walk(config.resolvedOutputDir)) {
    if (!path.endsWith("Options.ts")) continue;
    const content = await readFile(path, "utf8");
    existing.set(path, content);
    if (content.startsWith(owner) && !desired.has(path)) stale.push(path);
  }
  // Validate every destination before writing or pruning anything.
  for (const [path] of desired) {
    const physical = await physicalPath(path);
    if (!within(outputRoot, physical) || physical !== path)
      throw new Error(`Output path contains a symlink: ${path}`);
    const content =
      existing.get(path) ??
      (existsSync(path) ? await readFile(path, "utf8") : undefined);
    if (content !== undefined && !content.startsWith(owner))
      throw new Error(
        `Refusing to overwrite an unowned file: ${path}. Move legacy generated files before regenerating.`,
      );
  }
  const changed = [...desired].filter(
    ([path, content]) => existing.get(path) !== content,
  );
  if (check) {
    if (changed.length || stale.length)
      throw new Error(
        `Generated files are out of date (${changed.length} changed, ${stale.length} stale).`,
      );
  } else {
    for (const [path, content] of changed) await atomicWrite(path, content);
    for (const path of stale) await unlink(path);
  }
  console.log(
    `${check ? "Checked" : "Generated"} ${desired.size} files; ${changed.length} changed; ${stale.length} stale.`,
  );
}
function usage() {
  console.log(
    "Usage: react-query-helper init|generate|watch [--config <path>] [--check]",
  );
  console.log(
    "Aliases: --init, --generate, --watch, --help. --check is for generate only.",
  );
}
async function main() {
  const args = process.argv.slice(2);
  let command: string | undefined,
    configPath: string | undefined,
    check = false;
  for (let i = 0; i < args.length; i++) {
    const arg = args[i]!;
    if (arg === "--help" || arg === "-h" || arg === "help") {
      usage();
      return;
    }
    if (arg === "--config") {
      configPath = args[++i];
      if (!configPath || configPath.startsWith("--"))
        throw new Error("--config requires a path.");
    } else if (arg === "--check") check = true;
    else if (
      ["init", "generate", "watch", "--init", "--generate", "--watch"].includes(
        arg,
      ) &&
      !command
    )
      command = arg.replace(/^--/, "");
    else throw new Error(`Unknown or conflicting argument: ${arg}`);
  }
  if (!command) {
    if (args.length) throw new Error("Specify a command.");
    usage();
    return;
  }
  if (check && command !== "generate")
    throw new Error("--check requires generate.");
  if (command === "init") {
    const path = resolve(configPath ?? "rqh.config.ts");
    if (existsSync(path) || (!configPath && resolveConfigPath())) {
      console.log("Config already exists; nothing was overwritten.");
      return;
    }
    if (!/\.(ts|mts)$/.test(path))
      throw new Error("init creates a .ts or .mts config.");
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, configTemplate, { flag: "wx" });
    console.log(
      `Created ${path}. Set sourceDir, then run react-query-helper generate.`,
    );
    return;
  }
  let config = await loadConfig({ configPath });
  await generate(config, check);
  if (command !== "watch") return;
  const paths = (c: ResolvedAutoQueryConfig) =>
    [
      c.resolvedSourceDir,
      c.configPath,
      c.resolvedCustomAnalyzerPath,
      c.resolvedCustomTemplatePath,
    ].filter((p): p is string => !!p && isAbsolute(p));
  const watcher = watch(paths(config), {
    ignoreInitial: true,
    followSymlinks: false,
    ignored: (p) => within(config.resolvedOutputDir, resolve(p)),
    awaitWriteFinish: { stabilityThreshold: 100, pollInterval: 20 },
  });
  let pending = false,
    running = false,
    closing = false;
  let timer: ReturnType<typeof setTimeout> | undefined;
  let active = Promise.resolve();
  async function drain() {
    if (running || closing) return;
    running = true;
    try {
      while (pending && !closing) {
        pending = false;
        try {
          const next = await loadConfig({ configPath });
          await generate(next);
          const previous = paths(config);
          config = next;
          await watcher.unwatch(
            previous.filter((p) => !paths(next).includes(p)),
          );
          watcher.add(paths(next));
        } catch (error) {
          console.error(error instanceof Error ? error.message : error);
        }
      }
    } finally {
      running = false;
    }
  }
  watcher.on("all", () => {
    pending = true;
    clearTimeout(timer);
    timer = setTimeout(() => {
      if (!running) active = drain();
    }, 100);
  });
  watcher.on("error", (error) => {
    console.error(error);
    process.exitCode = 1;
    void close();
  });
  const close = async () => {
    closing = true;
    clearTimeout(timer);
    await watcher.close();
    await active;
  };
  process.once("SIGINT", () => void close());
  process.once("SIGTERM", () => void close());
  console.log(`Watching ${config.resolvedSourceDir}`);
}
main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
